---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-va-oct2-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-va-oct2-2 
  name: chatbot-va-oct2-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi