apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot-va-oct2-2 
  janus-idp.io/tekton: chatbot-va-oct2-2
  backstage.io/kubernetes-id: chatbot-va-oct2-2
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: chatbot-va-oct2-2
resources: 
- application-dev.yaml